[info]
monstercount=42
;OK
[monster0]
guid=3398313
type=50352
name=幽草
title=曼陀山庄传送人
pos_x=143
pos_z=159
dir=22.5
script_id=893267
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=50
;OK
[monster1]
guid=3398314
type=50351
name=王管家
title=曼陀山庄指路人
pos_x=135
pos_z=154
dir=27
script_id=893266
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster2]
guid=3398315
type=50360
name=王岳山
title=门派举荐人
pos_x=154
pos_z=135
dir=18
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster3]
guid=3398316
type=50382
name=王偃月
title=门派问鼎报名人
pos_x=127
pos_z=135
dir=0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=95

[monster4]
guid=3398317
type=50350
name=王安歌
title=曼陀山庄任务发布人
pos_x=129
pos_z=106
dir=27
script_id=893265
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster5]
guid=3398318
type=50347
name=王素商
title=曼陀山庄拜师人
pos_x=140
pos_z=88
dir=27
script_id=893262
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=95
;OK
[monster6]
guid=3398319
type=50346
name=王夫人
title=曼陀山庄庄主
pos_x=140
pos_z=75
dir=27
script_id=893261
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=99
;OK
[monster7]
guid=3398320
type=50361
name=阳春
title=山庄亲卫
pos_x=138
pos_z=73
dir=27
script_id=893276
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster8]
guid=3398321
type=50362
name=白雪
title=山庄亲卫
pos_x=142
pos_z=73
dir=27
script_id=893277
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster9]
guid=3398322
type=50348
name=王和铃
title=曼陀山庄武功传授人
pos_x=155
pos_z=114
dir=18
script_id=893263
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=95
;OK
[monster10]
guid=3398323
type=50354
name=叶婆婆
title=灵鹄饲养员
pos_x=63
pos_z=132
dir= 0
script_id=893269
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=50
;OK
[monster11]
guid=3398324
type=50355
name=子衿
title=
pos_x=63
pos_z=137
dir= 13.5
script_id=893270
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=50
;OK
[monster12]
guid=3398325
type=50374
name=苏酥
title=
pos_x=63
pos_z=140
dir= 27
script_id=893285
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster13]
guid=3398326
type=50272
name=王雁足
title=曼陀山庄轻功传授人
pos_x=151
pos_z=36
dir= 27
script_id=893264
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster14]
guid=3398327
type=50353
name=王律之
title=山庄戍卫总领
pos_x=157
pos_z=164
dir= 30.5
script_id=893278
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=95
;OK
[monster15]
guid=3398328
type=50356
name=关山月
title=
pos_x=210
pos_z=158
dir= 22.5
script_id=893354
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=95
;OK
[monster16]
guid=3398329
type=50357
name=王水风
title=
pos_x=186
pos_z=171
dir= 0
script_id=893355
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=50

[monster17]
guid=3398330
type=50358
name=嵇聆风
title=晚籁武道长老
pos_x=185
pos_z=142
dir= 9
script_id=893273
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60

[monster18]
guid=3398331
type=50359
name=嵇扶光
title=昭明武道长老
pos_x=183
pos_z=132
dir= 0
script_id=893274
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster19]
guid=3398332
type=50363
name=王叠涓
title=斫琴师
pos_x=30
pos_z=197
dir= 0
script_id=893268
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster20]
guid=3398333
type=50364
name=严妈妈
title=
pos_x=228
pos_z=196
dir= 9
script_id=893292
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster21]
guid=3398334
type=50365
name=王语嫣
title=
pos_x=179
pos_z=79
dir= 22.5
script_id=893288
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster22]
guid=3398335
type=50375
name=王凝悦
title=
pos_x=181
pos_z=79
dir= 22.5
script_id=893289
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster23]
guid=3398336
type=50366
name=王离忧
title=
pos_x=61
pos_z=65
dir= 4.5
script_id=893281
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster24]
guid=3398337
type=50367
name=王灵均
title=
pos_x=231
pos_z=79
dir= 30.5
script_id=893282
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=60
;OK
[monster25]
guid=3398338
type=50370
name=王星浪
title=
pos_x=231
pos_z=178
dir= 27
script_id=893271
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster26]
guid=3398339
type=50371
name=花照水
title=
pos_x=225
pos_z=149
dir= 13.5
script_id=893292
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30

[monster27]
guid=3398340
type=50372
name=柳扶风
title=
pos_x=125
pos_z=199
dir= 27
script_id=893291
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster28]
guid=3398341
type=50373
name=陶岭
title=
pos_x=62
pos_z=191
dir= 13.5
script_id=893279
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=40
;OK
[monster29]
guid=3398342
type=50376
name=王绾绾
title=
pos_x=188
pos_z=69
dir= 0
script_id=893287
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster30]
guid=3398343
type=50377
name=王易简
title=
pos_x=176
pos_z=63
dir= 30.5
script_id=893286
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster31]
guid=3398344
type=50378
name=祈福台
title=
pos_x=191
pos_z=144
dir= 13.5
script_id=893293
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30
;OK
[monster32]
guid=3398345
type=50368
name=王岚别
title=
pos_x=135
pos_z=35
dir= 27
script_id=893283
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=0
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=40
;OK
[monster33]
guid=3398346
type=50369
name=王云聚
title=
pos_x=139
pos_z=159
dir= 27
script_id=893284
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=30

[monster34]
guid=3398347
type=50832
name=灵鹄
title=
pos_x=59
pos_z=137
dir= 0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=-1

[monster35]
guid=3398349
type=50833
name=衔月鹄
title=
pos_x=59
pos_z=133
dir= 0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=-1

[monster36]
guid=3398350
type=50833
name=衔月鹄
title=
pos_x=59
pos_z=129
dir= 0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=-1

[monster37]
guid=3398351
type=50832
name=灵鹄
title=
pos_x=59
pos_z=125
dir= 0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=-1

[monster38]
guid=3398352
type=50834
name=问情鹄
title=
pos_x=62
pos_z=129
dir= 30.5
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=0
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=-1

[monster39]
guid=3398353
type=50379
name=
title=
pos_x=69
pos_z=79
dir=0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=-1
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=1

[monster40]
guid=3398354
type=50380
name=
title=
pos_x=194
pos_z=84
dir=0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=-1
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=1

[monster41]
guid=3398355
type=50381
name=
title=
pos_x=127
pos_z=173
dir=0
script_id=-1
respawn_time=1000
group_id=-1
team_id=-1
base_ai=3
ai_file=-1
patrol_id=-1
shop0=-1
shop1=-1
shop2=-1
shop3=-1
ReputationID=-1
level=1
