[INFO]
PATROLNUMBER=8

[PATROL0]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
DeleteAtEndPoint=1	;在终点删除自己
POSX0=140
POSZ0=64
POSX1=132
POSZ1=56
settletime1=3000
scriptid=891063

[PATROL1]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
DeleteAtEndPoint=1	;在终点删除自己
POSX0=142
POSZ0=63
POSX1=133
POSZ1=54
settletime1=3000
scriptid=891064
;驯兽师雄鹰北
[PATROL2]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
POSX0=143
POSZ0=51
POSX1=143
POSZ1=66
;驯兽师雄鹰南
[PATROL3]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
POSX0=143
POSZ0=79
POSX1=143
POSZ1=66
;驯兽师雄鹰西
[PATROL4]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
POSX0=129
POSZ0=66
POSX1=143
POSZ1=66
;驯兽师雄鹰东
[PATROL5]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
POSX0=156
POSZ0=66
POSX1=143
POSZ1=66
;两个动物离开
[PATROL6]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
DeleteAtEndPoint=1	;在终点删除自己
POSX0=132
POSZ0=56
POSX1=114
POSZ1=37
settletime1=3000

[PATROL7]
PATROLPOINTNUM=2
isturnback=0		;是否要回头走,0:不回头
DeleteAtEndPoint=1	;在终点删除自己
POSX0=133
POSZ0=54
POSX1=114
POSZ1=37
settletime1=3000
