[KFSQuality]
;低级重洗
LowKFS_GorwRate0=738
LowKFS_GorwRate1=200
LowKFS_GorwRate2=50
LowKFS_GorwRate3=9
LowKFS_GorwRate4=2
LowKFS_GorwRate5=1
;高级重洗
HighKFS_GorwRate0=0
HighKFS_GorwRate1=875
HighKFS_GorwRate2=100
HighKFS_GorwRate3=18
HighKFS_GorwRate4=6
HighKFS_GorwRate5=1
