[System]
LoginID=1					;当前Login服务器端程序的LoginID
DBName=tlbbdb_main
DBUser=root
DBPassword=tl3264884
ClientVersion=1005
DBConnectCount=10
TurnPlayerCount=100
CryptPwd=0
ProxyConnect=0
EnableLicense=0
;反复登录的20S限制
ReLoginLimit=0
ReLoginStop=0
ReLoginStopTime=60000
;安全登录标记
NotifySafeSign=0
