;普通区服2
[System]
Desc0=功能：配置服务器端程序的相关情况；
Desc1=IP0、Port0指外网的地址和端口；
Desc2=IP1、Port1指内网的地址和端口；
Desc3=Type：Game=0；Login=1；

;当前服务器ID，（0，1，3，0根据服务器定）														  
CurrentServerID=0  
;当前游戏世界的服务器端程序数量
ServerNumber=2
;当前是否为T服
CurrentTServer=0
;允许加入T服通信
EnableInTServer=1

[World]
IP=127.0.0.1
Port=7777

[Redis]
IP=127.0.0.1
Port=6379
Password=Tlbb3264884

[Billing]
Number=1
IP0=192.168.1.198
Port0=9470
IP1=127.0.0.1
Port1=10101
IP2=127.0.0.1
Port2=10101
IP3=127.0.0.1
Port3=10101
IP4=127.0.0.1
Port4=10101

[Server0]
;游戏服务器端程序号
ServerID=0				
;此游戏服务器端程序所在的服务器号
MachineID=0				
;外网IP地址，用与客户端连接
IP0=127.0.0.1
;外网端口
Port0=9996
;内网IP地址，用与服务器端程序间连接
IP1=127.0.0.1
;内网端口
Port1=5000				
;服务器端程序类型，如: GameServer,LoginServer...
Type=0					
;ShareMemory共享Key
HumanSMKey=1001
;玩家商店共享Key
PlayShopSMKey=4001
;物品序号
ItemSerialKey=7001
;寄售商店Key
CommisionShopKey=6001
;元宝交易市场Key
AuctionKey=11001
;服务器等级Key
ServerLevelKey=13001
;CTU
CTUKey=14001

[Server1]
;游戏服务器端程序号
ServerID=1				
;此游戏服务器端程序所在的服务器号
MachineID=0				
;外网IP地址，用与客户端连接
IP0=127.0.0.1	
;外网端口
Port0=9995
;内网IP地址，用与服务器端程序间连接
IP1=127.0.0.1
;内网端口
Port1=4000				
;服务器端程序类型，如: GameServer,LoginServer...
Type=1					
;ShareMemory共享Key
HumanSMKey=1001
;玩家商店共享Key
PlayShopSMKey=4001
;物品序号
ItemSerialKey=7001
;寄售商店Key
CommisionShopKey=6001
;元宝交易市场Key
AuctionKey=11001
;服务器等级Key
ServerLevelKey=13001
;CTU
CTUKey=14001
