[System]
;区服数据库
DBName=tlbbdb_world							;ODBC连接名
DBUser=root									;用户名
DBPassword=tl3264884		;密码
;角色数据库
CharDBName=tlbbdb_main						;ODBC连接名
CharDBUser=root								;用户名
CharDBPassword=tl3264884	;密码
[ShareMem]
KeyCount=14
Key0=1001
Type0=1     ;HumanSMU
Interval0=30000				;数据存盘时间(毫秒）
Key1=2001
Type1=2     ;GuildSMU
Interval1=600000			;数据存盘时间(毫秒）
Key2=3001
Type2=3     ;MailSMU
Interval2=600000			;数据存盘时间(毫秒）
Key3=4001
Type3=4     ;PlayerShopSM
Interval3=1800000			;数据存盘时间(毫秒）
Key4=5001
Type4=5     ;GlobalDataSMU
Interval4=300000			;数据存盘时间(毫秒）
Key5=6001
Type5=6     ;CommisionShopSMU
Interval5=600000			;数据存盘时间(毫秒）
Key6=7001
Type6=7     ;ItemSerialKeySMU
Interval6=600000			;数据存盘时间(毫秒）
Key7=8001
Type7=8     ;PetProcreateItemSM
Interval7=600000			;数据存盘时间(毫秒）
Key8=9001
Type8=9     ;CitySMU
Interval8=600000			;数据存盘时间(毫秒）
Key9=10001
Type9=10    ;GuildLeagueSMU
Interval9=600000			;数据存盘时间(毫秒）
Key10=11001
Type10=11   ;AuctionSMU
Interval10=300000			;数据存盘时间(毫秒）
Key11=12001
Type11=12   ;TopListSMU
Interval11=600000			;数据存盘时间(毫秒）
Key12=13001
Type12=13   ;ServerLevelSMU
Interval12=600000			;数据存盘时间(毫秒）
Key13=14001
Type13=14  	;CTUSMU
Interval13=60000			;数据存盘时间(毫秒）
