[TopList]
TopListCount=3				;排行榜数据数量

;时间配置均为unix时间戳 可前往https://www.jyshare.com/front-end/852/转换
;花序榜·步花间
[TopList0]
time_start=1758096000	;开始时间
time_end=1758124799		;结束时间
;花序榜·醉花阴
[TopList2]
time_start=1758124800	;开始时间
time_end=1758297599		;结束时间
;花序榜·鸳鸯梦
[TopList1]
time_start=1758297600	;开始时间
time_end=1758470399		;结束时间
